section \<open>Normal Full-alphabet Angelic Merges\<close>

theory utp_ades_parallel_normal
  imports utp_ades_parallel_generic
begin

text \<open>
  Slicewise A3-healthiness alone does not supply a common singleton witness
  after existentially choosing the two branch observations.  We therefore
  use a stronger, normal-design condition: failure is independent of the
  final choice set, and successful observations are generated by singleton
  choices.  This condition simultaneously supplies A, A2, and A3.  It does
  not require the merge to return the prior state.
\<close>

abbreviation ades_normal_input :: "'s astate \<Rightarrow> 's astate des_vars_ext" where
  "ades_normal_input s0 \<equiv> \<lparr>ok\<^sub>v = True, \<dots> = s0\<rparr>"

abbreviation ades_normal_output :: "bool \<Rightarrow> 's set \<Rightarrow> 's achoices des_vars_ext" where
  "ades_normal_output b X \<equiv>
    \<lparr>ok\<^sub>v = b, \<dots> = \<lparr>ac\<^sub>v = X, \<dots> = ()\<rparr>\<rparr>"

definition normal_ades ::
  "('s astate \<Rightarrow> bool) \<Rightarrow>
   ('s astate \<Rightarrow> 's \<Rightarrow> bool) \<Rightarrow> 's angelic_design" where
  [pred]: "normal_ades F G =
    ((\<lambda>(s0, out). \<not> F s0) \<turnstile>\<^sub>r
     (\<lambda>(s0, out). \<exists>z \<in> achoices.ac\<^sub>v out. G s0 z))"

lemma normal_ades_eval:
  "normal_ades F G (x, out) \<longleftrightarrow>
    (\<not> des_vars.ok\<^sub>v x \<or> F (des_vars.more x) \<or>
     (des_vars.ok\<^sub>v out \<and>
      (\<exists>z \<in> achoices.ac\<^sub>v (des_vars.more out). G (des_vars.more x) z)))"
  by (simp add: normal_ades_def; pred_auto)

lemma normal_ades_is_H [closure]: "normal_ades F G is \<^bold>H"
  by (simp only: normal_ades_def rdesign_is_H1_H2)

lemma normal_ades_is_A0 [closure]: "normal_ades F G is A0"
  by (simp add: A0_healthy_obs_iff normal_ades_eval)

lemma normal_ades_is_PBMH_ades [closure]: "normal_ades F G is PBMH_ades"
  by (rule Healthy_intro, rule ades_obs_ext;
      auto simp add: PBMH_ades_obs normal_ades_eval; blast)

lemma normal_ades_is_A [closure]: "normal_ades F G is A"
  by (simp add: Healthy_def' A_def
      A1_eq_PBMH_ades[OF normal_ades_is_H]
      Healthy_if[OF normal_ades_is_PBMH_ades]
      Healthy_if[OF normal_ades_is_A0])

lemma normal_ades_is_A2 [closure]: "normal_ades F G is A2"
  by (rule Healthy_intro, rule ades_obs_ext;
      auto simp add: A2_obs normal_ades_eval)

lemma normal_ades_is_A3 [closure]: "normal_ades F G is A3"
proof (rule H_A3_intro[OF normal_ades_is_H], rule arel_indep_A3_rel)
  fix s0 a b
  show "pre\<^sub>D (normal_ades F G) (s0, a) =
        pre\<^sub>D (normal_ades F G) (s0, b)"
    by (simp add: normal_ades_def)
qed

text \<open>
  AN2 extracts failure from the started, nonterminating empty-choice
  observation.  It extracts each successful singleton from the started,
  terminating singleton observation.  These observations are tests on the
  supplied predicate, so no additional witness function is needed.
\<close>

definition AN2 :: "'s angelic_design \<Rightarrow> 's angelic_design" where
  [pred]: "AN2 P = normal_ades
    (\<lambda>s0. P (ades_normal_input s0, ades_normal_output False {}))
    (\<lambda>s0 z. P (ades_normal_input s0, ades_normal_output True {z}))"

lemma AN2_normal_ades [simp]: "AN2 (normal_ades F G) = normal_ades F G"
  by (auto simp add: AN2_def fun_eq_iff normal_ades_eval split: prod.splits)

lemma AN2_idem: "AN2 (AN2 P) = AN2 P"
  by (simp only: AN2_def[of P] AN2_normal_ades)

lemma AN2_Idempotent [closure]: "Idempotent AN2"
  by (simp add: Idempotent_def AN2_idem)

lemma AN2_mono: "P \<sqsubseteq> Q \<Longrightarrow> AN2 P \<sqsubseteq> AN2 Q"
  by (auto simp add: AN2_def normal_ades_eval pred_refine_iff
      split: prod.splits)

lemma AN2_Monotonic [closure]: "Monotonic AN2"
  by (rule MonotonicI, rule AN2_mono)

lemma AN2_healthy [closure]: "AN2 P is AN2"
  by (simp add: Healthy_def' AN2_idem)

lemma AN2_is_A [closure]: "AN2 P is A"
  by (simp only: AN2_def normal_ades_is_A)

lemma AN2_is_A2 [closure]: "AN2 P is A2"
  by (simp only: AN2_def normal_ades_is_A2)

lemma AN2_is_A3 [closure]: "AN2 P is A3"
  by (simp only: AN2_def normal_ades_is_A3)

text \<open>
  A3M is sufficient but not weakest for A3 closure with H1-healthy operands,
  even when A and A2 closure are also required. It enforces the normal form
  of AN2 on every branch slice. As a mathematical counterexample to necessity,
  M(x,p,q,o) = (not ok(x) and p = o and q = o) yields not ok(x) for all such
  operands. That result is A-, A2-, and A3-healthy, while M fails H1M and
  therefore A3M. This counterexample is explanatory; it is not mechanised
  as a separate lemma here.
\<close>

definition A3M :: "'s ades_merge_rel \<Rightarrow> 's ades_merge_rel" where
  [pred]: "A3M = merge_health AN2"

lemma A3M_slice [simp]: "merge_slice (A3M M) p q = AN2 (merge_slice M p q)"
  by (simp add: A3M_def)

lemma A3M_eval:
  "ades_merge_eval (A3M M) x p q out \<longleftrightarrow>
    (\<not> des_vars.ok\<^sub>v x \<or>
     ades_merge_eval M (ades_normal_input (des_vars.more x)) p q
       (ades_normal_output False {}) \<or>
     (des_vars.ok\<^sub>v out \<and>
      (\<exists>z \<in> achoices.ac\<^sub>v (des_vars.more out).
        ades_merge_eval M (ades_normal_input (des_vars.more x)) p q
          (ades_normal_output True {z}))))"
  by (simp add: A3M_def merge_health_eval AN2_def normal_ades_eval)

lemma A3M_idem: "A3M (A3M M) = A3M M"
  by (simp only: A3M_def; rule merge_health_idem[OF AN2_Idempotent])

lemma A3M_Idempotent [closure]: "Idempotent A3M"
  by (simp add: Idempotent_def A3M_idem)

lemma A3M_mono: "M \<sqsubseteq> N \<Longrightarrow> A3M M \<sqsubseteq> A3M N"
  unfolding A3M_def by (rule merge_health_mono[OF AN2_Monotonic]; assumption)

lemma A3M_Monotonic [closure]: "Monotonic A3M"
  by (rule MonotonicI, rule A3M_mono)

lemma A3M_healthy [closure]: "A3M M is A3M"
  by (simp add: Healthy_def' A3M_idem)

lemma A3M_healthy_iff:
  "M is A3M \<longleftrightarrow> (\<forall>p q. merge_slice M p q is AN2)"
  by (simp add: A3M_def merge_health_healthy_iff)

lemma A3M_is_ADM [closure]: "A3M M is ADM"
  by (simp add: ADM_healthy_iff AN2_is_A)

lemma A3M_is_A2M [closure]: "A3M M is A2M"
  by (simp add: A2M_healthy_iff AN2_is_A2)

text \<open>
  For a concrete non-skip instance, normalise the existing right-branch
  merge.  With singleton branch choices it permits the right result 2 and
  rejects the prior state 0.  Thus the combined A/A2/A3 condition does not
  collapse full merges to skip.
\<close>

lemma A3M_right_non_skip:
  defines "x \<equiv> ades_normal_input (StateII (0 :: nat))"
    and "p \<equiv> ades_normal_output True {1 :: nat}"
    and "q \<equiv> ades_normal_output True {2 :: nat}"
  shows "ades_merge_eval (A3M (merge_ades_up ades_right_merge)) x p q
           (ades_normal_output True {2})"
    and "\<not> ades_merge_eval (A3M (merge_ades_up ades_right_merge)) x p q
           (ades_normal_output True {0})"
  by (simp_all add: x_def p_def q_def A3M_eval
      merge_ades_up_def ades_merge_image_def
      ades_right_merge_def StateII_def)

lemma A3M_right_branch_dependence:
  defines "x \<equiv> ades_normal_input (StateII (0 :: nat))"
    and "p \<equiv> ades_normal_output True {1 :: nat}"
  shows "ades_merge_eval (A3M (merge_ades_up ades_right_merge)) x p
           (ades_normal_output True {2}) (ades_normal_output True {2})"
    and "\<not> ades_merge_eval (A3M (merge_ades_up ades_right_merge)) x p
           (ades_normal_output True {3}) (ades_normal_output True {2})"
  by (simp_all add: x_def p_def A3M_eval
      merge_ades_up_def ades_merge_image_def ades_right_merge_def StateII_def)

text \<open>
  The repair also need not retain conjunction of the branch termination
  flags.  A permitted failure is independent of the final observation, as
  required by this normal-design class, and therefore permits both values
  of the final termination flag.
\<close>

lemma A3M_right_relaxes_ok_conjunction:
  defines "x \<equiv> ades_normal_input (StateII (0 :: nat))"
    and "p \<equiv> ades_normal_output False ({} :: nat set)"
    and "q \<equiv> ades_normal_output True {2 :: nat}"
  shows "ades_merge_eval (A3M (merge_ades_up ades_right_merge)) x p q
           (ades_normal_output True {2})"
    and "\<not> ades_merge_eval (merge_ades_up ades_right_merge) x p q
           (ades_normal_output True {2})"
  by (simp_all add: x_def p_def q_def A3M_eval
      merge_ades_up_def ades_merge_image_def ades_right_merge_def StateII_def)

subsection \<open>A Healthy Symmetric Merge Need Not Be Associative\<close>

text \<open>
  A Boolean example separates healthiness and symmetry from associativity.
  Each operand offers one Boolean value. On started inputs the merge reads
  exact singleton branch observations and offers their NAND. The exact
  singleton tests keep the calculation deterministic even though healthy
  output predicates also accept larger choice sets. Every merge slice has
  normal_ades form, so the merge satisfies A3M, ADM, and A2M.
\<close>

definition ades_bool_choice :: "bool \<Rightarrow> bool angelic_design" where
  [pred]: "ades_bool_choice b =
    normal_ades (\<lambda>_. False) (\<lambda>_ z. z = b)"

lemma ades_bool_choice_eval:
  "ades_bool_choice b (x,out) \<longleftrightarrow>
    (\<not> des_vars.ok\<^sub>v x \<or>
     (des_vars.ok\<^sub>v out \<and> b \<in> achoices.ac\<^sub>v (des_vars.more out)))"
  by (simp add: ades_bool_choice_def normal_ades_eval)

lemma ades_bool_choice_healthy [closure]:
  "ades_bool_choice b is A"
  "ades_bool_choice b is A2"
  "ades_bool_choice b is A3"
  by (simp_all add: ades_bool_choice_def normal_ades_is_A
      normal_ades_is_A2 normal_ades_is_A3)

definition ades_nand_merge :: "bool ades_merge_rel" where
  [pred]: "ades_nand_merge = (\<lambda>(m,out).
    normal_ades (\<lambda>_. False)
      (\<lambda>_ z. \<exists>a b.
        mrg_left\<^sub>v m = ades_normal_output True {a} \<and>
        mrg_right\<^sub>v m = ades_normal_output True {b} \<and>
        z = (\<not> (a \<and> b)))
      (mrg_prior\<^sub>v m,out))"

lemma ades_nand_merge_slice [simp]:
  "merge_slice ades_nand_merge p q =
    normal_ades (\<lambda>_. False)
      (\<lambda>_ z. \<exists>a b.
        p = ades_normal_output True {a} \<and>
        q = ades_normal_output True {b} \<and> z = (\<not> (a \<and> b)))"
  by (simp add: merge_slice_def ades_nand_merge_def fun_eq_iff)

lemma ades_nand_merge_eval:
  "ades_merge_eval ades_nand_merge x p q out \<longleftrightarrow>
    (\<not> des_vars.ok\<^sub>v x \<or>
     (des_vars.ok\<^sub>v out \<and> (\<exists>a b.
       p = ades_normal_output True {a} \<and>
       q = ades_normal_output True {b} \<and>
       (\<not> (a \<and> b)) \<in> achoices.ac\<^sub>v (des_vars.more out))))"
  by (simp add: ades_nand_merge_def normal_ades_eval; blast)

lemma ades_nand_merge_is_A3M [closure]: "ades_nand_merge is A3M"
  unfolding A3M_healthy_iff
  by (simp add: Healthy_def')

lemma ades_nand_merge_is_ADM [closure]: "ades_nand_merge is ADM"
  by (simp add: ADM_healthy_iff normal_ades_is_A)

lemma ades_nand_merge_is_A2M [closure]: "ades_nand_merge is A2M"
  by (simp add: A2M_healthy_iff normal_ades_is_A2)

lemma ades_nand_merge_symmetric: "MergeSym ades_nand_merge"
  unfolding MergeSym_def
  by (simp only: ades_nand_merge_eval; fastforce simp: conj_commute)

lemma ADOKM_ades_nand_merge: "ADOKM ades_nand_merge = ades_nand_merge"
  by (rule merge_slice_ext, rule ades_obs_ext;
      auto simp: ADOKM_eval ades_nand_merge_eval normal_ades_eval)

lemma ades_par_full_nand_eval:
  "ades_par_full P ades_nand_merge Q (x,out) =
    (\<exists>p q. P (x,p) \<and> Q (x,q) \<and> ades_merge_eval ades_nand_merge x p q out)"
  by (subst ades_par_full_eval; simp only: ADOKM_ades_nand_merge)

lemma ades_nand_parallel:
  "ades_par_full (ades_bool_choice a) ades_nand_merge (ades_bool_choice b) =
    ades_bool_choice (\<not> (a \<and> b))"
proof (rule ades_obs_ext)
  fix started s0 terminated X
  show "ades_par_full (ades_bool_choice a) ades_nand_merge (ades_bool_choice b)
      (ades_obs started s0 terminated X) =
    ades_bool_choice (\<not> (a \<and> b)) (ades_obs started s0 terminated X)"
  proof (cases started)
    case False
    then show ?thesis
      by (simp add: ades_par_full_nand_eval ades_bool_choice_eval ades_nand_merge_eval)
  next
    case True
    show ?thesis
    proof
      assume "ades_par_full (ades_bool_choice a) ades_nand_merge (ades_bool_choice b)
        (ades_obs started s0 terminated X)"
      then obtain p q where
        P: "ades_bool_choice a (ades_normal_input (StateII s0),p)" and
        Q: "ades_bool_choice b (ades_normal_input (StateII s0),q)" and
        M: "ades_merge_eval ades_nand_merge (ades_normal_input (StateII s0)) p q
          (ades_normal_output terminated X)"
        using True by (auto simp only: ades_par_full_nand_eval StateII_def)
      from M obtain u v where
        p: "p = ades_normal_output True {u}" and
        q: "q = ades_normal_output True {v}" and
        result: "terminated \<and> (\<not> (u \<and> v)) \<in> X"
        by (auto simp add: ades_nand_merge_eval)
      show "ades_bool_choice (\<not> (a \<and> b)) (ades_obs started s0 terminated X)"
        using P Q p q result True by (auto simp add: ades_bool_choice_eval)
    next
      assume result: "ades_bool_choice (\<not> (a \<and> b))
        (ades_obs started s0 terminated X)"
      have P: "ades_bool_choice a
        (ades_normal_input (StateII s0), ades_normal_output True {a})"
        by (simp add: ades_bool_choice_eval)
      have Q: "ades_bool_choice b
        (ades_normal_input (StateII s0), ades_normal_output True {b})"
        by (simp add: ades_bool_choice_eval)
      have M: "ades_merge_eval ades_nand_merge (ades_normal_input (StateII s0))
        (ades_normal_output True {a}) (ades_normal_output True {b})
        (ades_normal_output terminated X)"
        using result True
        by (auto simp add: ades_nand_merge_eval ades_bool_choice_eval)
      show "ades_par_full (ades_bool_choice a) ades_nand_merge (ades_bool_choice b)
        (ades_obs started s0 terminated X)"
        using P Q M True by (auto simp only: ades_par_full_nand_eval StateII_def)
    qed
  qed
qed

lemma ades_bool_choice_eq_iff:
  "ades_bool_choice a = ades_bool_choice b \<longleftrightarrow> a = b"
proof
  assume eq: "ades_bool_choice a = ades_bool_choice b"
  from fun_cong[OF eq, of "(ades_normal_input (StateII False),
    ades_normal_output True {a})"]
  show "a = b" by (auto simp add: ades_bool_choice_eval)
next
  assume "a = b"
  then show "ades_bool_choice a = ades_bool_choice b" by simp
qed

lemma ades_nand_parallel_not_assoc:
  "ades_par_full
      (ades_par_full (ades_bool_choice True) ades_nand_merge (ades_bool_choice True))
      ades_nand_merge (ades_bool_choice False) \<noteq>
    ades_par_full (ades_bool_choice True) ades_nand_merge
      (ades_par_full (ades_bool_choice True) ades_nand_merge (ades_bool_choice False))"
  by (simp add: ades_nand_parallel ades_bool_choice_eq_iff)

lemma ades_nand_merge_not_associative: "\<not> MergeAssoc ades_nand_merge"
proof
  assume assms: "MergeAssoc ades_nand_merge"
  have "ades_par_full
      (ades_par_full (ades_bool_choice True) ades_nand_merge (ades_bool_choice True))
      ades_nand_merge (ades_bool_choice False) =
    ades_par_full (ades_bool_choice True) ades_nand_merge
      (ades_par_full (ades_bool_choice True) ades_nand_merge (ades_bool_choice False))"
    by (rule ades_par_full_assoc; simp add: ADOKM_ades_nand_merge assms)
  with ades_nand_parallel_not_assoc show False by contradiction
qed

subsection \<open>Normal Conjunctive-ok Merges\<close>

definition ANOKM :: "'s ades_merge_rel \<Rightarrow> 's ades_merge_rel" where
  [pred]: "ANOKM = A3M \<circ> OkM"

lemma ANOKM_eval:
  "ades_merge_eval (ANOKM M) x p q out \<longleftrightarrow>
    (\<not> des_vars.ok\<^sub>v x \<or>
      (if des_vars.ok\<^sub>v p \<and> des_vars.ok\<^sub>v q
       then des_vars.ok\<^sub>v out \<and>
         (\<exists>z \<in> achoices.ac\<^sub>v (des_vars.more out).
           ades_merge_eval M (ades_normal_input (des_vars.more x)) p q
             (ades_normal_output True {z}))
       else ades_merge_eval M (ades_normal_input (des_vars.more x)) p q
         (ades_normal_output False {})))"
  by (auto simp: ANOKM_def A3M_eval OkM_eval)

lemma ANOKM_idem: "ANOKM (ANOKM M) = ANOKM M"
  by (rule merge_slice_ext, rule ades_obs_ext;
      auto simp: ANOKM_eval)

lemma ANOKM_Idempotent [closure]: "Idempotent ANOKM"
  by (simp add: Idempotent_def ANOKM_idem)

lemma ANOKM_mono: "M \<sqsubseteq> N \<Longrightarrow> ANOKM M \<sqsubseteq> ANOKM N"
  unfolding ANOKM_def comp_apply by (intro A3M_mono OkM_mono)

lemma ANOKM_Monotonic [closure]: "Monotonic ANOKM"
  by (rule MonotonicI, rule ANOKM_mono)

lemma ANOKM_healthy [closure]: "ANOKM M is ANOKM"
  by (simp add: Healthy_def' ANOKM_idem)

lemma ANOKM_is_A3M [closure]: "ANOKM M is A3M"
  by (simp add: ANOKM_def A3M_healthy)

subsection \<open>Symmetry and Non-skip Examples\<close>

lemma ANOKM_MergeSym: "MergeSym M \<Longrightarrow> MergeSym (ANOKM M)"
  unfolding ANOKM_def comp_apply A3M_def
  by (intro merge_health_MergeSym OkM_MergeSym)

lemma ANOKM_state_lift:
  "ANOKM (merge_ades_up j) = A3M (merge_ades_up j)"
  by (simp add: ANOKM_def)

lemmas ANOKM_right_non_skip = A3M_right_non_skip[folded ANOKM_state_lift]
lemmas ANOKM_right_branch_dependence =
  A3M_right_branch_dependence[folded ANOKM_state_lift]
lemmas ANOKM_right_relaxes_ok_conjunction =
  A3M_right_relaxes_ok_conjunction[folded ANOKM_state_lift]

text \<open>
  The right-merge examples retain branch dependence, accept a result
  different from the prior state, and exhibit the deliberate relaxation
  of the seed's ok equation after normalisation. No new state-level
  totality or functionality premise is used by the closure results above.
\<close>

lemma ADOKM_ANOKM_absorb: "ADOKM (ANOKM M) = ANOKM M"
  by (rule merge_slice_ext, rule ades_obs_ext;
      auto simp: ADOKM_eval ANOKM_eval)

lemma ades_par_full_ANOKM_form:
  assumes "P is H1" "Q is H1"
  shows "ades_par_full P (ANOKM M) Q = normal_ades
    (\<lambda>s0. \<exists>p q. P (ades_normal_input s0,p) \<and>
      Q (ades_normal_input s0,q) \<and>
      ades_merge_eval (OkM M) (ades_normal_input s0) p q (ades_normal_output False {}))
    (\<lambda>s0 z. \<exists>p q. P (ades_normal_input s0,p) \<and>
      Q (ades_normal_input s0,q) \<and>
      ades_merge_eval (OkM M) (ades_normal_input s0) p q (ades_normal_output True {z}))"
proof -
  have eval: "ades_par_full P (ANOKM M) Q (x,out) =
    (\<exists>p q. P (x,p) \<and> Q (x,q) \<and> ades_merge_eval (ANOKM M) x p q out)" for x out
    by (subst ades_par_full_eval; simp only: ADOKM_ANOKM_absorb)
  have P_unstarted: "\<not> des_vars.ok\<^sub>v x \<Longrightarrow> P (x,p)" for x p
  proof -
    assume "\<not> des_vars.ok\<^sub>v x"
    then have "H1 P (x,p)" by (simp add: H1_def; pred_auto)
    then show "P (x,p)" by (simp only: Healthy_if[OF assms(1)])
  qed
  have Q_unstarted: "\<not> des_vars.ok\<^sub>v x \<Longrightarrow> Q (x,q)" for x q
  proof -
    assume "\<not> des_vars.ok\<^sub>v x"
    then have "H1 Q (x,q)" by (simp add: H1_def; pred_auto)
    then show "Q (x,q)" by (simp only: Healthy_if[OF assms(2)])
  qed
  show ?thesis
    apply (rule ades_obs_ext)
    subgoal for b s0 c X
      apply (cases b; auto simp add: eval ANOKM_eval OkM_eval normal_ades_eval P_unstarted Q_unstarted)
      by blast
    done
qed

lemma ades_par_full_ANOKM_closure:
  assumes "P is H1" "Q is H1"
  shows "ades_par_full P (ANOKM M) Q is A"
    and "ades_par_full P (ANOKM M) Q is A2"
    and "ades_par_full P (ANOKM M) Q is A3"
  by (simp_all only: ades_par_full_ANOKM_form[OF assms]
      normal_ades_is_A normal_ades_is_A2 normal_ades_is_A3)

end
